name: Automerge Feature
on:
  push:
    branches:
      - "feature/*"
jobs:
  pruebas-flask:
    name: Pruebas Flask
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Instalación de librerías y dependencias de python
        run: |
          python -m pip install --upgrade pip
          pip install -r flaskr/requirements.txt
      - name: Correr pruebas de flask
        id: correr-pruebas
        run: python -m unittest discover -s flaskr/tests
      - name: Restaurar db
        id: restaurar-db
        run: git checkout HEAD -- flaskr/tutorial_canciones.db
  pruebas-angular:
    name: Pruebas Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de entorno de angular
        uses: actions/setup-node@v2
        with:
          node-version: "14.15"
      - name: Instalacion de librerías y dependencias de angular
        run: |
          cd ./front-end/tutorial-canciones/
          npm i
          npm install -g @angular/cli
      - name: Instalacion de Google Chrome para pruebas de angular
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: beta
      - name: Corre pruebas de angular
        run: |
          cd front-end/tutorial-canciones/ && CHROMIUM_BIN=$(which chrome) ng test --watch=false --browsers=ChromeHeadless
  check-commit:
    name: Check Commit Message
    needs:
      - pruebas-flask
      - pruebas-angular
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^MERGE:*"
          error: "The last push of this feature is not ready to be merged with the develop branch"
  automerge:
    name: Automerge
    needs:
      - check-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge feature to develop branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: dev
          github_token: ${{ github.token }}
